### ISSUE TITLE
Cleanup: Damage class

### ISSUE THREAD

**Issue by JuliaScythe** [TheWelshEngineer/DQ-Redux#1]
The `Damage` class can be extended to clean up places where it's used, by:
- implementing toString rather than having giant if statements in the client
- adding a function (perhaps static) that takes a Damage and a Creature (or maybe IDamageable if things other than creatures can be damaged) and returns the amount of damage it takes.

**Comment by TheWelshEngineer** [comment]
Update - need to subclass out damage types in order to assign status types
