### ISSUE TITLE
Unify Resistances

### ISSUE THREAD

**Issue by BenTaylor25** [TheWelshEngineer/DQ-Redux#18]
In the referenced code, you are creating an ArrayList to combine several independent properties.

This tells me that the properties shouldn't be independent - consider unifying the resistance types together into one class.
This way, whenever you need `resistances` you already have it, and whenever you need to reference a particular resistance type, you can access it directly through the collection `shield.immuneChaosDamage()` -> `shield.resistances.immuneChaosDamage()`.

(Or rather `shield.getResistances().isImmuneChaosDamage()` so that the the `shield` can monitor the access to `shield.resistances`).

I have highlighted `resistances` in particular, but this also applies to `imunities` and possibly others.

https://github.com/TheWelshEngineer/DQ-Redux/blob/44410c8fe57c3bfc3fc51d2c2b6ef18900aea2f3/src/RogueLike/Main/Creature.java#L1100

**Comment by diamond-deluxe** [comment]
Closed by #49.
