### ISSUE TITLE
Stacking in [b]ackpack doesn't work correctly

### ISSUE THREAD

**Issue by diamond-deluxe** [TheWelshEngineer/DQ-Redux#35]
![image](https://github.com/TheWelshEngineer/DQ-Redux/assets/112557036/c2b7faf4-2f95-4d69-9226-e9eba79174dc)

Example in screenshot. Note that rations stack correctly, individual pickups of stacked ammo (the flintlock bullets) have separate stacks, and other items such as potions don't stack.

**Comment by TheWelshEngineer** [comment]
Creature item stacking method was reliant on old, non-futureproofed item ID counts
