### ISSUE TITLE
Throw command appears twice in backpack; can't throw from backpack.

### ISSUE THREAD

**Issue by diamond-deluxe** [TheWelshEngineer/DQ-Redux#40]
![image](https://github.com/TheWelshEngineer/DQ-Redux/assets/112557036/d2580665-ab1b-4e69-ba71-b63d5d43a2a6)

See screenshot. When selecting a throwable weapon in the backpack, the `[T]: Throw` hint appears twice. 

Also, pressing `T` here doesn't actually do anything. Combined with #36, this means that it's impossible to use thrown weapons when you have over 26 items in inventory.

**Comment by TheWelshEngineer** [comment]
Text was being rendered according to incorrect conditions, causing an overlap

Logic for throwing items from the backpack was entirely missing
